### ISSUE TITLE
Carrion Golem and increased buff effect of golems

### ISSUE THREAD

**Issue by bukowa** [Openarl/PathOfBuilding#1666]
For example "Golem Commander" passive. It gains "increased effect of buffs granted by your golems" but in POB it does not change the dmg for other minions types like zombies. Should it?

**Comment by Openarl** [comment]
Fixed in the next update.

**Comment by Tikia** [comment]
Hi,
There is still an issue with that Golem.
I use a Primordial Harmony Cobalt Jewel, when I active my Carrion Golem, DPS of my 6L Golem don't change (it's work for all other golems).
Can you have a look at it ?

**Comment by Tikia** [comment]
> 
> 
> Fixed in the next update.

Hi,
There is still an issue with that Golem.
I use a Primordial Harmony Cobalt Jewel, when I active my Carrion Golem, DPS of my 6L Golem don't change (it's work for all other golems).
Can you have a look at it ?
