### ISSUE TITLE
[BUG] Update to the latest version (from 1.0.0 and 1.0.2, zip) leads to update error and app crush on launch

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#3]
After trying to update current version (downloaded zip, not installer) I've got next error:
![Updater error](http://i.imgur.com/rfz71Fn.png)

Can guess that it because I don't have "Path of Building" folder on that path:
![No folder](http://i.imgur.com/13jadhu.png)

Sadly, there are no ways to fix it and that leads to app crash on launch:
![App crash](http://i.imgur.com/nuouc1Z.png)

**Comment by Openarl** [comment]
Sorry about that! Seems I neglected to test the update function on the standalone version.
The bug should be fixed now; you'll need to re-extract the zip file and start the program again to get the fixed version.

**Comment by dein0s** [comment]
Update error gone, but app still crashes.
Unpacked zip in a new directory, started PoB.exe as administrator, update went smooth, but then again:
![App crash](http://i.imgur.com/367CT42.png)

**Comment by dein0s** [comment]
@Openarl can we continue here or should I open a new issue?

**Comment by Openarl** [comment]
We'll continue here, since it looks like the first crash is still occurring. Not sure where the crash is coming from at the moment; it looks like it's crashing very early in the program initialization, which is odd as there's not much going on at that point.

**Comment by Openarl** [comment]
Could you try something for me? I just need to rule out one possibility.

Extract ONLY "SimpleGraphic.dll" from the zip and try running the program. If it does start, don't click Apply Update because it'll replace it again.

**Comment by bloxed** [comment]
I was having the same issue he was describing, extracting SimpleGraphic.dll to replace the new one fixed the issue. Hope this information helps.

**Comment by Openarl** [comment]
It does indeed! I've only made one change in that dll once since the initial release, so that must be the culprit. Not sure why that change is causing the crash though; it was intended to fix another bug that someone was having. I'll need to investigate further.

**Comment by Openarl** [comment]
I've just pushed another update that may resolve this crash. Please let me know if it works!

**Comment by dein0s** [comment]
Sorry for the late answer, was a bit afk.
I can confirm that replacing current "SimpleGraphic.dll" with dll from zip solves the problem.

Going to check your last update now. Can I safely press 'Apply Update' button?

**Comment by Openarl** [comment]
Yep, go for it. It will download the version that I just put up.

**Comment by bloxed** [comment]
Crashing persists with the most recent update

**Comment by dein0s** [comment]
Ok, so now step by step:

1. Extracted 1.0.0 from zip
2. Started PoB.exe
3. After update was done it crashed
4. Replaced dll once again
5. Started PoB.exe
6. Launched successfully (ver 1.0.9)
7. Pressed 'Apply Update' button
8. Crashed again

**Comment by Openarl** [comment]
Damn. Looks like I'll have to revert the earlier change until I figure out another way of fixing the bug it was intended to fix. But before I do that I'd like for one of you to try out this version of the DLL, just to make sure.
[SimpleGraphic.zip](https://github.com/Openarl/PathOfBuilding/files/447273/SimpleGraphic.zip)

**Comment by dein0s** [comment]
1. Extracted your dll into the last folder (step 8 from prev comment)
2. Started PoB.exe
3. Launched successfully (ver 1.0.9)
4. Pressed 'Apply Update' button
5. Crashed again

Any other specific conditions you want to test it with?

**Comment by Openarl** [comment]
Ok, is there any text in the console window when the crash occurs? I saw that there wasn't in the first screenshots but I made a minor change in the DLL version that I just provided which may cause some text to show up. I need to know if that text is there!

**Comment by Openarl** [comment]
Oh sorry, I should have mentioned, after extracting the DLL I gave you, you must not click Apply Update or it'll overwrite it.

**Comment by dein0s** [comment]
W/o clicking 'Apply Update' it acts like the original ones (from 1.0.0 zip) - app launching successfully.

**Comment by Openarl** [comment]
Ahh excellent! So that means the version I gave you is good. Well, I now know exactly what's causing the crash, but not why. That's something I'll need to look into later. For now, I'll be pushing an update containing the version I gave you, so you'll be able to safely update the program.

**Comment by dein0s** [comment]
Great, thanks.
And you really have to add some debug mode with log output :) So users can provide much more helpfull info on their issues.

I'm somehow familiar with lua (back to old 2000 and WoW addons), but things happening around now totally looks like some dark fcking magic to me :D

**Comment by dein0s** [comment]
And reporting success here.
V 1.0.10 updated without any problems ,yay!

**Comment by Openarl** [comment]
Good to hear!
RE debug mode... the thing is, it does actually have such a mode, but in this case the program was crashing before any of that was set up. It would initialize the debug console, create the main window in the background, and then immediately crash. The cause turned out to be the particular set of window styles on the main window, but god only knows why...

**Comment by dein0s** [comment]
Okey then.
If you'll need further testing on this - let me know.

**Comment by Openarl** [comment]
Ok thanks; I may need to take you up on that offer sometime because I'll be damned if I can get this crash to occur on my system. I'm currently going through the code again to see if I can pinpoint any possible crash triggers.

**Comment by Openarl** [comment]
Ok, found and corrected 2 possible triggers. Could you please try out this version?
[SimpleGraphic.zip](https://github.com/Openarl/PathOfBuilding/files/447435/SimpleGraphic.zip)
And again, I just need to know if it starts up successfully with this DLL.

**Comment by dein0s** [comment]
Sure. Will report in a few mins.

**Comment by dein0s** [comment]
Nope, it didn't work. Crashed.
And there were no any console with text in it, jsut to mention.

**Comment by Openarl** [comment]
Daaaamn. Ok this has got me stumped. I'll have to come back to this another day.
You'll need to extract one of the working versions to get it going again.
Thanks for your help!

**Comment by dein0s** [comment]
And... Crash is back to business again with v 1.0.11 update :|

**Comment by Openarl** [comment]
Oooh boy here we go again :(. I think I may have pushed the wrong version of the DLL with the latest update; I've reissued it with the proper version now. Let me know if it's fixed.

**Comment by dein0s** [comment]
Yep, fixed for now.

**Comment by Openarl** [comment]
Ok good, closing this for now.
